# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: Huan
name: Huan's Blog
title: Huan
email: fredwanghuan(at)gmail(dot)com
description: >- # this means to ignore newlines until next top-level key
  It's not that learning is fun, but not knowing is not fun.

# the subpath of your site, e.g. /blog
baseurl: ""

# the base hostname & protocol for your site, e.g. http://example.com
url: ""

github_username:  fredwangwang

# statistics
revolvermaps: TODO

# comment
disqus:
  enable: false
  account_name: fredwanghuan # https://<account_name>.disqus.com

# Build settings
markdown: kramdown

# Plugins are defined in Gemfile `group :jekyll_plugins`

# Exclude from processing.
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

permalink: /:categories/:title
